language: java

# Skip 'mvn install', not really needed for our tests
install: "echo 'Skipping install, dependencies will be downloaded during build and test.'"

# Build and test 
#  travis_retry = retry build/test up to 3 times
#  -B = batch/non-interactive mode (recommended for CI)
#  -V = display version info before build
script: "travis_retry mvn clean package license:check -Dmaven.test.skip=false -B -V"

# Give Maven 2GB of memory to work with
env: MAVEN_OPTS=-Xmx2048M
